---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bases-microservice
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: bases-microservice
  interval: 30s
  targetNamespace: staging
  values:
    image:
      tag: 0.0.1
    ingress:
      host: staging.devops-toolkit.172.21.0.2.xip.io

